<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="LAPTOP-OV4RUVE6" name="b4_iRetryAnalyzer.A1_SampleRetryTest" tests="6" failures="0" timestamp="28 Dec 2022 04:31:13 GMT" time="0.034" errors="1">
  <testcase name="loginTest" time="0.002" classname="b4_iRetryAnalyzer.A1_SampleRetryTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.023" classname="b4_iRetryAnalyzer.A1_SampleRetryTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.001" classname="b4_iRetryAnalyzer.A1_SampleRetryTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.003" classname="b4_iRetryAnalyzer.A1_SampleRetryTest">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zeroat b4_iRetryAnalyzer.A1_SampleRetryTest.loginTest(A1_SampleRetryTest.java:17)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.002" classname="b4_iRetryAnalyzer.A1_SampleRetryTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.003" classname="b4_iRetryAnalyzer.A1_SampleRetryTest">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- b4_iRetryAnalyzer.A1_SampleRetryTest -->
